### ISSUE TITLE
Add `#[proc_macro_derive(Absorb)]` on custom structs

### ISSUE THREAD

**Issue by mmagician** [arkworks-rs/crypto-primitives#133]
So that we can write:
```
#[dervice(Absorb)]
struct MyStruct {
    a: u8,
    b: u8,
}
```

What do you think? Happy to take it on

**Comment by Pratyush** [comment]
That would be great!

Would also be great for traits in `r1cs-std`, like `AllocVar`, `R1CSVar`, `EqGadget`, `CmpGadget`, etc.
