### ISSUE TITLE
An update to Nonnative has broken the library

### ISSUE THREAD

**Issue by Will-Lin4** [arkworks-rs/crypto-primitives#25]
`get_params` now requires three arguments in Nonnative, so this line is incorrect:
https://github.com/arkworks-rs/crypto-primitives/blob/fde39ab764f00e28b2f292af3706a2654ea55edb/src/snark/constraints.rs#L464

**Comment by weikengchen** [comment]
I forgot that it is also used here. I am on the way asap.

**Comment by weikengchen** [comment]
Done. Sorry again!

**Comment by Will-Lin4** [comment]
Thanks!
