### ISSUE TITLE
`cargo build --features=r1cs --no-default-features` fails

### ISSUE THREAD

**Issue by zhenfeizhang** [arkworks-rs/crypto-primitives#51]
seems like [this file](https://github.com/arkworks-rs/crypto-primitives/blob/main/src/encryption/elgamal/constraints.rs) relies on `std`. can be fixed with 
```
use ark_std::vec::Vec;
```

**Comment by zhenfeizhang** [comment]
related to this, CI https://github.com/arkworks-rs/crypto-primitives/blob/3a83d9ff29f529b04c9f7862e1a2a6f15312df85/.github/workflows/ci.yml#L120
seems to missed the `r1cs` gate and did not check all the `constraint.rs`

**Comment by Pratyush** [comment]
cc @weikengchen

**Comment by weikengchen** [comment]
Thanks for catching this. I will update soon
